---
swagger: "2.0"
info:
  description: "This is a detailed ChapiVentas"
  version: "1.0.0"
  title: "ChapiVentas API"
basePath: "/api"
schemes:
- "http"
consumes:
  - application/json
paths:
  /carrera:
    post:
      tags:
      - "Carrera"
      summary: "Crear carrera"
      description: "Crear carrera"
      operationId: "postCarrera"
      parameters:
      - name: "Carrera"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/Carrera"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
      - "Carrera"
      summary: "Obtener carreras"
      description: "Obtener todas las carreras."
      operationId: "listUsersGET"
      responses:
        200:
          description: "Carreras"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Carrera"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
  /promocion:
    post:
      tags:
      - "Promocion"
      summary: "Crear Promocion"
      description: "Crear promocion con fecha inicial y final"
      operationId: "postPromocion"
      parameters:
      - name: "Promocion"
        in: "body"
        description: "Login object"
        required: true
        schema:
          $ref: "#/definitions/Promocion"

      responses:
        200:
          description: ""
          schema:
            type: "string"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
      - "Promocion"
      summary: "Obtener todas las promociones entre fechas"
      description: "Obtener todas las promociones  dentro el rango especificado"
      operationId: "listUsersGET"
      parameters:
      - name: 'fechaInicio'
        in: 'query'
        description: 'Fecha inicial Promo'
        required: true
        example: '2017-08-02'
        type: 'string'
      - name: 'fechaFinal'
        in: 'query'
        description: 'Fecha Final Promo'
        required: true
        example: '2017-08-02'
        type: string
      responses:
        200:
          description: "Promocion"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Promocion"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Promocion:
    type: object
    properties:
      tipo:
        type: string
      descuento:
        type: number
      descripcion:
        type: string
      fechaInicioPromo:
        type: string
      fechaFinalPromo:
        type: string
  Carrera:
    type: object
    properties:
      nombre:
        type: string
      descripcion:
        type: string
      estudiantes:
        type: integer

  Error:
    type: "object"
    properties:
      code:
        type: "integer"
      index:
        type: integer
      errmsg:
        type: "string"
      op:
        type: "array"
        items:
          type: "string"
